manifest = "dc36458a4545d8bcc1acaa58c26669621bbcf592cdf4d197ac54ce3c62d6325a"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.49.0" ]
revision = "d3a4298d018723c63cbecab085f0aa8a6e2e6211"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.49.0" ]
revision = "72b1919a324229aafc0c3c805ec8e22b985fcbeb"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.49.0" ]
revision = "63176e5e4eef9e85cbb2d42119475a0f5e80e03b"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.49.0" ]
revision = "5303008d2190d8ba849831783ae3357c9d91425f"
