targets = ["//:utility"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.49.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.49.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
version = "1.49.0"