manifest = "9009031ddd6914ea24fddaedc0226cc5cda74af29be4845101018c72d2094046"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.28.0" ]
revision = "e5f044291adec7ee599144608ac5856151558dae"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.28.0" ]
revision = "a5243efdf3ec2871379224c5e71cb3280548cfec"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.28.0" ]
revision = "69c26afa48b73ecd1f97182480f419bf8a5bd9f0"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.28.0" ]
revision = "b7bbe4aea8b0d9d79ee9a67d65070c9ac56d974c"
