manifest = "1bdfb677a24dcce12ef3c9dde3efab6502e69b98a935fba06f6dd4242f52fcd6"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.56.0" ]
revision = "9d1a6e0a4a74ad3af0ade7285ab5edd52c6fd860"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.56.0" ]
revision = "edb8562f816250216903f89ec4d9ac0961a922a1"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.56.0" ]
revision = "599096bd0a9ca5ecd901886f09046e3f7ce05556"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.56.0" ]
revision = "baeb2fb09197e1422a40481e9080e17c75cd50cf"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.56.0" ]
revision = "ad21a117be237ab693f723782c5581bb58ce8875"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.56.0" ]
revision = "9641085a42a25ca196d08d542862616f877cf693"
