manifest = "facc42af01d1a87704d01f032b740648f857276a5e07fe1d235d37201cff14db"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.24.0" ]
revision = "37278170bcbe6e22f6eebed0d33d5df4e0d015e1"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.24.0" ]
revision = "9bde767a62803ab4aa713772d98815bd948d9d47"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.24.0" ]
revision = "36d22132d39fc31e27c7ba1f61d91b294e12aa78"
