manifest = "24f13ecd25bac15bf35b0f54d75d02879fd568032b8198959b4ba91cfb9293b8"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.65.0" ]
revision = "d464187703a522223f9f3b01b4fbe8f8ae05fad6"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.65.0" ]
revision = "7268ab966b715d5702f1a2b98990626f1c193e6f"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.65.0" ]
revision = "296264e87d794813a2c6681e56ca783560d4961d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.65.0" ]
revision = "2c6eae3c5a1b1278f35ea09e2df05f59c9303b12"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.65.0" ]
revision = "312cb1699e9fbeb0ee859791f57290f6196a0eef"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.65.0" ]
revision = "32153d21d6a4f5a334d859adb7acb2d005a190ff"
