manifest = "e91b60a206dafbb39fae61f873679bcfb461cb85af0d7638bd9dbc6a5aa510b9"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.18.2" ]
revision = "2bf83561dbe29c6a2f97e701b97009e21c960172"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.18.2" ]
revision = "d8760c9173c351453b4512c800eae5a663b3c6fb"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.18.2" ]
revision = "3cd4197a52549145514ab2f5bfeeb104ad0d0e54"
