manifest = "14b1e03cfed6f91115f0295e4a381dad870a40f11c464d8e90fd69f129812f59"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.30.2" ]
revision = "0368528c3989e727bd67b791b31fcf415b6311ac"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.30.2" ]
revision = "e3cdd8edf43fef5fb442d3ca3f724dd0ec83152b"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.30.2" ]
revision = "4569928373f56cb8d74f8de43bbfc5e2bc08c30c"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.30.2" ]
revision = "9495f6210ed7b740349301fb164c9b3dc3a7c634"
