targets = [ "//:utility" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "branch=master"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
version = "branch=master"
