manifest = "d49ec40ffb1dcae0175af8dc7044edb03bfef684347a501787d19f60754faceb"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.32.0" ]
revision = "e5568ba0d052a0f81d93328d0e233167b3a0210a"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.32.0" ]
revision = "748a263ebf5f23d60f0af1716368d84251bf1f39"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.32.0" ]
revision = "c231ec4059c26c890e22aead63a38f6e6c1b5d08"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.32.0" ]
revision = "c24fe2ccfaa5c9f492b578edde614575cd549a68"
