manifest = "b106ce8179aae2432d10fc5564cc28ba771823cdd4b0c3f713ef26dd8932d1b5"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.60.0" ]
revision = "30200cca26f795f074c8cde1612e7ca3e991c6dd"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.60.0" ]
revision = "2cd181f656b7f927f015f31509c278c2f31fb797"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.60.0" ]
revision = "a925c01c552ca5d288538be0f0e16557f35f02ea"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.60.0" ]
revision = "e795f285a98323376ee89e6d825c8113c14decdd"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.60.0" ]
revision = "755e1c862e2ad626b448c19c0cd416585c8966e1"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.60.0" ]
revision = "a242146f8aa7a5529e75dd9ca56121a608511720"
