manifest = "a8fe879610ced89dcd804f16ef4aa1bec9e21814c7485e269b09b1167b84d07b"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.67.0" ]
revision = "d33f5202a6d3d8e42cccd641c8d78e7b467fec8d"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.67.0" ]
revision = "5782f108397199eccd4404780d37513b42798a43"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.67.0" ]
revision = "205cacd6bff72f09635287926d379c56ec87899d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.67.0" ]
revision = "feb7fef2d9afa1f1e2f33d4a6a2d9d63aadd1d24"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.67.0" ]
revision = "aa51a0a1e2936c78fa448bdada5a0ca6754f0b54"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.67.0" ]
revision = "7554865aad1e357c2ce1300060e87f1f44f9d3b0"
