manifest = "86a3581c76c9a197f9edb4298f99cdfb94dfb145dc74a495eb97465505e2e8e1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.43.0" ]
revision = "b372c24ab8b55df3a336bc4f0b200014369d6d96"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.43.0" ]
revision = "77ca029d6666ae6c9d11b7fae0f2c6424020fead"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.43.0" ]
revision = "71e2798b88ab175cc2c904a8d1863b69a02f9a09"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.43.0" ]
revision = "ef5e2df9e921bb8120a0d80847731139e0e37d7d"
