manifest = "d3be4018609d135ac98664f934abf5f74c8bd47c1c02478eaf7aeba1e464067a"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.64.0" ]
revision = "e3fa47a21cd2ac5e967de7a1ce612ff22aef9196"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.64.0" ]
revision = "9cbe0f1be39466ec9b76b35b81295959fd417de0"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.64.0" ]
revision = "d2d531ddc041d4f15d72a5932846557e873422a4"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.64.0" ]
revision = "fea9d446679bef8b8273c3c71c9dbf9af5f4ee1d"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.64.0" ]
revision = "db820029d840e07d89f1e4d0faadbeec6ea0b3d4"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.64.0" ]
revision = "f77b6125bb376584bc51fd31a134d0ad36a9077f"
