manifest = "27713bd907fe74f5cbb8aaae042f667bb9f491a04a173ec07b63fcb480907668"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.65.1" ]
revision = "f52c6500fd6e7409de7724611f7e6ece82702aa4"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.65.1" ]
revision = "ef899f910b922b982581c55683d22a30ed10e2ab"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.65.1" ]
revision = "2800c1da8c0a7690f1b2984df9de9863096ee22e"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.65.1" ]
revision = "dfd1a8c32d76184a8ffe83d63c3a216303dc9085"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.65.1" ]
revision = "53c1a2e2b254dd5a3512c71b223e5a48bedcc3a7"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.65.1" ]
revision = "6e6c057b13b5f61e6157330ec30fe6cc3e8503b8"
